### ISSUE TITLE
Exclude patches marked as [WIP]

### ISSUE THREAD

**Issue by andreaskienast** [andygrunwald/gotrap#1]
Please exclude patches that start with [WIP] in the subject line. Verifying them does not make much sense :)

Examples:
- [[WIP][!!!][TASK] Refactor EXT:workspaces](https://review.typo3.org/#/c/36451/)
- [[WIP][FEATURE] RequireJs support for FE](https://review.typo3.org/#/c/36857/)

**Comment by andygrunwald** [comment]
Thanks for this!
Are they more "patterns" to exclude for TYPO3.CMS ?
I will solve it via the regex lib:
See http://play.golang.org/p/YB8ucbKsoD as an example

**Comment by andygrunwald** [comment]
Output logging looks like

```
2015/05/16 10:57:18 > Skipped AMQP message (uncovered message type: ref-replication-done)
2015/05/16 10:57:18 > New patchset-created message incoming for ref "refs/changes/18/32718/3" in "Packages/TYPO3.CMS" (http://review.typo3.org/32718)
2015/05/16 10:57:18 > Subject "[WIP][BUGFIX] Fix translations handling for file references in Extbase" excluded by pattern "^\[WIP\].*"
2015/05/16 10:57:18 > Skipped AMQP message (uncovered message type: ref-replicated)
```

**Comment by andygrunwald** [comment]
Thanks for your suggestion. If you got more feel free to add a new issue :)
Documentation, how to use this feature, will be implemented in https://github.com/andygrunwald/gotrap/issues/5
