### ISSUE TITLE
Don't give V-1 on allowed failures

### ISSUE THREAD

**Issue by andreaskienast** [andygrunwald/gotrap#2]
Currently, a patch is marked as "non verified" if Travis crashes at allowed failures.

Affected patch: [[BUGFIX] Fix regression in GeneralUtility::rmFromList()](https://review.typo3.org/#/c/36967/)
Travis: [51120029](https://travis-ci.org/typo3-ci/TYPO3.CMS-pre-merge-tests/builds/51120029)

**Comment by andygrunwald** [comment]
@andreasfernandez Currently i can`t reproduce this anymore.
It seems like a temporary hick up.

I refactored the code a lot and didn`t saw such a behaviour.
Should we agree on a "can`t reproduce" until it comes back?

**Comment by andreaskienast** [comment]
@andygrunwald I'm fine with "can't reproduce", I'll post in ticket if this happens again.
